### ISSUE TITLE
Update pop up ui at the end of a round before it is displayed

### ISSUE THREAD

**Issue by BoxThatBeat** [Math3808Team/UltimateTexasHoldem#31]
In the constructor of EndOfRoundDialogWindow, use the provided roundResults to update the ui elements (payouts, the player and house's trick, total payout). The pop up ui has a default look to it right now as seen below. Update text to be green when in positive and red when decreasing and white when 0. The QStrings used for the labels can be made using this method:
ui->AntePayout->setText(QStringLiteral("%1 $%2").arg('-').arg(roundResult.antePayout * -1)); (example for if the value is negative)

![image](https://user-images.githubusercontent.com/28713093/114633904-6b563400-9c8f-11eb-9581-8c436b7b04ec.png)

**Comment by Grandduchy** [comment]
Merged by commits dd8e4d2397fc4d3f86c4b6fd7571fda56f5eda73, e2e0f7954756d62404fc29a960fa32953d182a23 and 7ae993e7b15143cd8cc5e69690a8720a6f6eb5fe
